kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eurynome-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: eurynome-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurynome-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eurynome-db
    spec:
      volumes:
        - name: eurynome-pvc
          persistentVolumeClaim:
            claimName: eurynome-pvc
      containers:
        - name: container
          image: docker.io/mysql:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: eurynome
            - name: MYSQL_USER
              value: eurynomeuser
            - name: MYSQL_PASSWORD
              value: eurynomepw
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - name: eurynome-pvc
              mountPath: /var/lib/mysql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: eurynome-db
spec:
  selector:
    app: eurynome-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP