kind: Deployment
apiVersion: apps/v1
metadata:
  name: debezium
  namespace: rohmer12u-dev
  uid: f7ef1701-9de3-4141-9621-4c565f09b185
  resourceVersion: '7276442954'
  generation: 4
  creationTimestamp: '2026-02-13T14:02:22Z'
  annotations:
    deployment.kubernetes.io/revision: '2'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2026-02-13T14:05:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"container"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:env':
                    'k:{"name":"STATUS_STORAGE_TOPIC"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_PRODUCER_SECURITY_PROTOCOL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"OFFSET_STORAGE_TOPIC"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_CONSUMER_SASL_JAAS_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_CONSUMER_SASL_MECHANISM"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_CONSUMER_SECURITY_PROTOCOL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_PRODUCER_SASL_JAAS_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_PRODUCER_SASL_MECHANISM"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"BOOTSTRAP_SERVERS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONFIG_STORAGE_TOPIC"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_SECURITY_PROTOCOL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_SASL_JAAS_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CONNECT_SASL_MECHANISM"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GROUP_ID"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8083,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2026-02-13T14:06:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debezium
    spec:
      containers:
        - name: container
          image: quay.io/debezium/connect
          ports:
            - containerPort: 8083
              protocol: TCP
          env:
            - name: GROUP_ID
              value: '1'
            - name: STATUS_STORAGE_TOPIC
              value: my_connect_statuses
            - name: OFFSET_STORAGE_TOPIC
              value: my_connect_offsets
            - name: CONFIG_STORAGE_TOPIC
              value: my_connect_configs
            - name: BOOTSTRAP_SERVERS
              value: 'my-kafka.rohmer12u-dev.svc.cluster.local:9092'
            - name: CONNECT_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: CONNECT_SASL_MECHANISM
              value: SCRAM-SHA-256
            - name: CONNECT_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="N8zABq8Wm1";
            - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: CONNECT_PRODUCER_SASL_MECHANISM
              value: SCRAM-SHA-256
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="N8zABq8Wm1";
            - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: CONNECT_CONSUMER_SASL_MECHANISM
              value: SCRAM-SHA-256
            - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="N8zABq8Wm1";
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2026-02-13T14:05:09Z'
      lastTransitionTime: '2026-02-13T14:02:22Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "debezium-b99f8c599" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2026-02-13T14:06:44Z'
      lastTransitionTime: '2026-02-13T14:06:44Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
